### ISSUE TITLE
Styling of the code block disappears if i empty the footer content

### ISSUE THREAD

**Issue by prafulla-codes** [abelljs/abell-website#1]

**Comment by prafulla-codes** [comment]
![image](https://user-images.githubusercontent.com/36433104/85171986-bf6dd300-b28d-11ea-8b45-334eb01f9e82.png)

It disappears exactly when i remove copyright thing, is this a feature or a bug XD?

**Comment by prafulla-codes** [comment]
**Resolved**

This was because of the javascript associated in the static-main.js
![image](https://user-images.githubusercontent.com/36433104/85172168-27bcb480-b28e-11ea-9879-6e19b56bef15.png)

**Comment by saurabhdaware** [comment]
I don't know whats happening but I am just happy that you found a way out .__.

**Comment by prafulla-codes** [comment]
Yeah it seems you were too busy, so i had to solve my own problem 😂
