### ISSUE TITLE
Typing mistake in Tutorial -> Exploring the Starter section

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell-website#5]
This issue is only for first-time contributors. If you're someone who is comfortable with open-source, please look into other issues in this organizations.

![Abell Components have <template>, <style?, and <script> tag wrapped inside a <AbellComponent> tag.](https://user-images.githubusercontent.com/30949385/94370800-b5226700-010f-11eb-9b57-495fe3784421.png)

As you can see in the screenshot above, there is a line that says 
```
Abell Components have <template>, <style?, and <script> tag wrapped inside a <AbellComponent> tag.
```

It should be `<style>` instead.

*Note: This issue is only for the people who are not yet comfortable with open-source and especially for the people who have never contributed before. If you are experienced and if you can tackle other issues, I will highly suggest you to tackle other issues instead*

If you need any help, you can drop your questions here.

If you're interested in working on this issue, drop a comment here. (Maybe something like 'Meeeeeeeeeeeeeee')

**Comment by yoBoyio** [comment]
Meeeeeeeeeeeeeee

**Comment by saurabhdaware** [comment]
You can go ahead @yoBoyio :D Let me know if you need any help

**Comment by smksha** [comment]
Is the issue still open. May I take this as my first pull request on github ?

**Comment by saurabhdaware** [comment]
Hi @smksha  We have some more issues in https://abelljs.org/issue-finder?label=Hacktoberfest so you can check them out and let me know if you want to work on any of them. I will try to create some more issues later this and next month
