### ISSUE TITLE
Spelling mistake in Tutorial -> Dynamic Page Generation

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/abell-website#8]
![Note: Abell.meta is only avaible in .abell pages that are inside [path] directory](https://user-images.githubusercontent.com/30949385/94465770-0ac54500-01de-11eb-99c2-4fc7486ceca5.png)

Available is spelled as avaible in https://abelljs.org/tutorial/create-portfolio/#dynamic-page-generation-from-content

This issue is only for the first-time contributors

**Comment by saurabhdaware** [comment]
@smksha this is a similar issue like the one you were asking for . Would you like to work on this?

**Comment by ampsteric** [comment]
I would like to work on this issue sir. please assign it to me.

**Comment by saurabhdaware** [comment]
Hi, @ampsteric! This issue is mostly for the people who have never contributed to someone else's repository and who are fairly new to open-source. Assigning difficult issues to new people can be overwhelming so I'm keeping some issues specially for them.

You can contribute to any other issue in this organization that are not labeled with 'only for first-time contributors'. Hope you understand. Thanks :D 

Let me know if you need help with solving any other issue

**Comment by ampsteric** [comment]
Even I am a beginner. But I understand. cool

**Comment by xascript** [comment]
Hi @saurabhdaware ,

I would like to work on that issue. I'm also a beginner and have never contributed to an open source project.

**Comment by saurabhdaware** [comment]
Hi @aissak you can go ahead. Let me know if you need any help. Thank you so much!
